batch:
  path-pattern: file:/workspaces/notes/**/*.md
  extract-path: /update/extract
  cron: 0 0 * * * *
spring:
  batch:
    job:
      enabled: false
  data:
    solr:
      host: http://localhost:8983/solr